@echo off
echo [INFO] Starting JP Subtitle Generator...
echo [INFO] Working directory: D:\jp_subtitle_generator
cd /d "D:\jp_subtitle_generator"
echo [INFO] Activating virtual environment...
call venv\scripts\activate
echo [INFO] Launching server on port 7861...
python jp_subtitle_generator_web.py
