@echo off
echo [INFO] Starting iMerl Network...
echo [INFO] Working directory: D:\workplace\html-5-ai-commentator-workflow-tenant
cd /d D:\workplace\html-5-ai-commentator-workflow-tenant
echo [INFO] Activating virtual environment...
call venv\scripts\activate
echo [INFO] Launching server on port 8003...
python html/run.py
